<h1>Liczby</h1>

<p>Parzyste</p>
<ul>
    <?php foreach ($parzyste as $liczba):?>
        <li>
            <strong>
                <?=$liczba?>
            </strong>
        </li>
    <?php endforeach; ?>
</ul>
<p>Nieparzyste</p>
<ul>
    <?php foreach ($nieparzyste as $liczba):?>
        <li>
            <strong>
                <?=$liczba?>
            </strong>
        </li>
    <?php endforeach; ?>
</ul>