<?php
$this->headScript()->appendFile($this->basePath('/js/koszyk.js'), 'text/javascript', ['defer' => true]);
$form->setAttribute('action', $this->url('nieruchomosci/koszyk', []))
?>
<?= $this->form()->openTag($form) ?>
<h2 class="my-3">Koszyk użytkownika</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th><?= $form->get('typ_oferty')->getLabel() ?></th>
            <th><?= $form->get('typ_nieruchomosci')->getLabel() ?></th>
            <th><?= $form->get('numer')->getLabel() ?></th>
            <th><?= $form->get('powierzchnia')->getLabel() ?> </th>>
            <th><?= $form->get('powierzchniaMin')->getLabel() ?> </th>>
            <th><?= $form->get('powierzchniaMax')->getLabel() ?></th>
            <th><?= $form->get('cena')->getLabel() ?> </th>
            <th><?= $form->get('cenaMin')->getLabel() ?> </th>
            <th><?= $form->get('cenaMax')->getLabel() ?></th>
            <th></th>
        </tr>
        <tr class="szukaj">
            <th></th>
            <th><?= $this->formElement($form->get('typ_oferty')) ?></th>
            <th><?= $this->formElement($form->get('typ_nieruchomosci')) ?></th>
            <th><?= $this->formElement($form->get('numer')) ?></th>
            <th><?= $this->formElement($form->get('powierzchnia')) ?></th>
            <th><?= $this->formElement($form->get('powierzchniaMin')) ?></th>
            <th><?= $this->formElement($form->get('powierzchniaMax')) ?></th>
            <th><?= $this->formElement($form->get('cena')) ?></th>
            <th><?= $this->formElement($form->get('cenaMin')) ?></th>
            <th><?= $this->formElement($form->get('cenaMax')) ?></th>
            <th><?= $this->formSubmit($form->get('szukaj')) ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($oferty as $of): ?>
            <tr>
                <td><?= $of->id ?></td>
                <td><?= $of->typ_oferty ?></td>
                <td><?= $of->typ_nieruchomosci ?></td>
                <td><?= $of->numer ?></td>
                <td><?= $of->powierzchnia ?></td>
                <td>-</td>
                <td>-</td>
                <td><?= $of->cena ?></td>
                <td>-</td>
                <td>-</td>
                <td class="text-nowrap">
                    <a
                            href="<?= $this->url('nieruchomosci/oferty', ['action' => 'szczegoly', 'id' => $of->id]) ?>"
                            title="szczegóły"
                    ><i class="fas fa-folder-open"></i></a>
                    &nbsp;
                    <a
                            href="<?= $this->url('nieruchomosci/koszyk', ['action' => 'usun', 'id' => $of->id]) ?>"
                            title="usun z koszyka"
                            class="aUsunZKoszyka"
                    ><i class="fas fa-trash"></i></a>
                    &nbsp;
                    <a
                            href="<?= $this->url('nieruchomosci/oferty', ['action' => 'drukuj', 'id' => $of->id]) ?>"
                            title="drukuj"
                    ><i class="fas fa-print"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
</table>

<?= $this->paginationControl(
    $oferty, 
    'sliding', 
    ['partial/paginator.phtml', 'Nieruchomosci'], 
    ['route' => 'nieruchomosci/koszyk', 'parametry' => $parametry]
)
?>

<?= $this->form()->closeTag($form); ?>
<strong>Drukuj wszystko</strong>
<a href="<?= $this->url('nieruchomosci/oferty', ['action' => 'drukujWszystko']) ?>" title="drukuj"
><i class="fas fa-print"></i></a>